Models/View/Shared/Flash.cs
namespace CLAM.Models.View.Shared
{
    public class Flash
    {
        public string Message { get; set; }

        public FlashType Type { get; set; }
    }
}

Models/View/Shared/FlashType.cs
namespace CLAM.Models.View.Shared
{
    public enum FlashType
    {
        Success,
        Warning,
        Error
    }
}

Controllers/ClasController.cs
using CLAM.Extensions;
using CLAM.Models.View.Clas;
using CLAM.Models.View.Shared;
using CLAM.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CLAM.Controllers
{
    [Route("clas")]
    public class ClasController : Controller
    {
        public ClasController(ClaService claService)
        {
            ClaService = claService;
        }

        private ClaService ClaService { get; }

        [HttpGet, ActionName("Index"), Route("")]
        public async Task<IActionResult> GetIndex()
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var clas = await ClaService.List(email);

            return View(new Index
            {
                Clas = clas
            });
        }

        [HttpGet, ActionName("Create"), Route("create")]
        public IActionResult GetCreate()
        {
            return View();
        }

        [HttpPost, ActionName("Create"), Route("create")]
        public async Task<IActionResult> PostCreate(Create create)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            if (await ClaService.Create(email, create.Name, create.ApiKey))
            {
                TempData.AddFlash("Your CLA has been created", FlashType.Success);
            }
            else
            {
                TempData.AddFlash("Your CLA couldn't be created", FlashType.Error);
            }

            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("Show"), Route("{id}/show")]
        public async Task<IActionResult> GetShow(int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var cla = await ClaService.Single(email, id);

            if (cla == null)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Show
            {
                Id = cla.Id,
                Name = cla.Name,
                ApiKey = cla.ApiKey,
                Secret = cla.Secret,
                WebhookUrl = Url.Action("Webhook", "GitLab", new { claId = cla.Id }, HttpContext.Request.Scheme)
            });
        }

        [HttpGet, ActionName("Edit"), Route("{id}/edit")]
        public async Task<IActionResult> GetEdit(int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var cla = await ClaService.Single(email, id);

            if (cla == null)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Edit
            {
                Name = cla.Name,
                ApiKey = cla.ApiKey
            });
        }

        [HttpPost, ActionName("Edit"), Route("{id}/edit")]
        public async Task<IActionResult> PostEdit(int id, Edit edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            var success = await ClaService.Edit(email, id, edit.Name, edit.ApiKey);

            if (!success)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
            }
            else
            {
                TempData.AddFlash("The CLA has been updated", FlashType.Success);
            }

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Flashes.cshtml
@foreach (var flash in TempData.GetFlashes())
{
    switch (flash.Type)
    {
        case CLAM.Models.View.Shared.FlashType.Success:
            <div class="alert alert-success">@flash.Message</div>
            break;
        case CLAM.Models.View.Shared.FlashType.Warning:
            <div class="alert alert-warning">@flash.Message</div>
            break;
        case CLAM.Models.View.Shared.FlashType.Error:
            <div class="alert alert-danger">@flash.Message</div>
            break;
    }
}

Views/Shared/_Layout.cshtml
@{
    var title = ViewBag?.Title ?? "Unknown page";
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CLAM - @title</title>

    <link href="~/bundle.min.css" rel="stylesheet" asp-append-version="true">
    <script src="~/bundle.min.js" asp-append-version="true"></script>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">CLAM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="nav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Clas" asp-action="Index">CLAs</a>
                    </li>
                }
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Account</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Logout</a>
                        }
                        else
                        {
                            <a class="dropdown-item" asp-controller="Account" asp-action="Login">Login</a>
                            <a class="dropdown-item" asp-controller="Account" asp-action="Register">Register</a>
                        }
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <main class="container my-3">
        <partial name="_Flashes.cshtml">
            <div class="card">
                <div class="card-header">@title</div>
                <div class="card-body">
                    @RenderBody()
                </div>
                <div class="card-footer text-center text-muted">
                    CLAM
                </div>
            </div>
    </main>
</body>
</html>