Models/Database/Cla.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.Database
{
    public class Cla : IModel
    {
        public int Id { get; set; }

        [Required]
        public string ApiKey { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Secret { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime? ModifiedAt { get; set; }

        public DateTime? DeletedAt { get; set; }

        public List<UserCla> UserClas { get; set; }

        public static void ConfigureEntity(EntityTypeBuilder<Cla> builder)
        {
            builder.HasQueryFilter(u => !u.DeletedAt.HasValue);
        }
    }
}

Models/View/Clas/Create.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Clas
{
    public class Create
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }

        [Required, DisplayName("API key")]
        public string ApiKey { get; set; }
    }
}

Models/View/Clas/Edit.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Clas
{
    public class Edit
    {

        [Required, DisplayName("Name")]
        public string Name { get; set; }

        [Required, DisplayName("API key")]
        public string ApiKey { get; set; }
    }
}

Models/View/Clas/Index.cs
using CLAM.Models.Database;
using System.Collections.Generic;

namespace CLAM.Models.View.Clas
{
    public class Index
    {
        public List<Cla> Clas { get; set; }
    }
}

Models/View/Clas/Show.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Clas
{
    public class Show
    {
        public int Id { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("API key")]
        public string ApiKey { get; set; }

        [DisplayName("Webhook secret")]
        public string Secret { get; set; }

        [DataType(DataType.Url), DisplayName("Webhook URL")]
        public string WebhookUrl { get; set; }
    }
}

Models/View/Revisions/Create.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Revisions
{
    public class Create
    {
        [Required, DisplayName("Text")]
        public string Text { get; set; }

        [DisplayName("Require address")]
        public bool RequireAddress { get; set; }
    }
}

Models/View/Revisions/Show.cs
using System.ComponentModel;

namespace CLAM.Models.View.Revisions
{
    public class Show
    {
        public int ClaId { get; set; }

        public int Id { get; set; }

        [DisplayName("Revision")]
        public int Number { get; set; }

        [DisplayName("Text")]
        public string Text { get; set; }

        [DisplayName("Require address")]
        public bool RequireAddress { get; set; }
    }
}

Models/View/Signers/Show.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Signers
{
    public class Show
    {
        [DataType(DataType.EmailAddress), DisplayName("Email address")]
        public string Email { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Signed at")]
        public DateTime? SignedAt { get; set; }
    }
}

Controllers/ClasController.cs
using CLAM.Extensions;
using CLAM.Models.View.Clas;
using CLAM.Models.View.Shared;
using CLAM.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CLAM.Controllers
{
    [Route("clas")]
    public class ClasController : Controller
    {
        public ClasController(ClaService claService)
        {
            ClaService = claService;
        }

        private ClaService ClaService { get; }

        [HttpGet, ActionName("Index"), Route("")]
        public async Task<IActionResult> GetIndex()
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var clas = await ClaService.List(email);

            return View(new Index
            {
                Clas = clas
            });
        }

        [HttpGet, ActionName("Create"), Route("create")]
        public IActionResult GetCreate()
        {
            return View();
        }

        [HttpPost, ActionName("Create"), Route("create")]
        public async Task<IActionResult> PostCreate(Create create)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            if (await ClaService.Create(email, create.Name, create.ApiKey))
            {
                TempData.AddFlash("Your CLA has been created", FlashType.Success);
            }
            else
            {
                TempData.AddFlash("Your CLA couldn't be created", FlashType.Error);
            }

            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("Show"), Route("{id}/show")]
        public async Task<IActionResult> GetShow(int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var cla = await ClaService.Single(email, id);

            if (cla == null)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Show
            {
                Id = cla.Id,
                Name = cla.Name,
                ApiKey = cla.ApiKey,
                Secret = cla.Secret,
                WebhookUrl = Url.Action("Webhook", "GitLab", new { claId = cla.Id }, HttpContext.Request.Scheme)
            });
        }

        [HttpGet, ActionName("Edit"), Route("{id}/edit")]
        public async Task<IActionResult> GetEdit(int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var cla = await ClaService.Single(email, id);

            if (cla == null)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Edit
            {
                Name = cla.Name,
                ApiKey = cla.ApiKey
            });
        }

        [HttpPost, ActionName("Edit"), Route("{id}/edit")]
        public async Task<IActionResult> PostEdit(int id, Edit edit)
        {
            if (!ModelState.IsValid)
            {
                return View(edit);
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            var success = await ClaService.Edit(email, id, edit.Name, edit.ApiKey);

            if (!success)
            {
                TempData.AddFlash("The requested CLA doesn't exist", FlashType.Warning);
            }
            else
            {
                TempData.AddFlash("The CLA has been updated", FlashType.Success);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/RevisionsController.cs
using CLAM.Extensions;
using CLAM.Models.View.Revisions;
using CLAM.Models.View.Shared;
using CLAM.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CLAM.Controllers
{
    [Route("clas/{claId}/revisions")]
    public class RevisionsController : Controller
    {
        public RevisionsController(RevisionService revisionService)
        {
            RevisionService = revisionService;
        }

        public RevisionService RevisionService { get; }

        [HttpGet, ActionName("Index"), Route("")]
        public async Task<IActionResult> GetIndex(int claId)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var revisions = await RevisionService.List(email, claId);

            return View(new Index
            {
                Revisions = revisions
            });
        }

        [HttpGet, ActionName("Create"), Route("create")]
        public IActionResult GetCreate()
        {
            return View();
        }

        [HttpPost, ActionName("Create"), Route("create")]
        public async Task<IActionResult> PostCreate(int claId, Create create)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            if (await RevisionService.Create(email, claId, create.Text, create.RequireAddress))
            {
                TempData.AddFlash("Your revision has been created", FlashType.Success);
            }
            else
            {
                TempData.AddFlash("Your revision couldn't be created", FlashType.Error);
            }

            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("Show"), Route("{id}/show")]
        public async Task<IActionResult> GetShow(int claId, int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var revision = await RevisionService.Single(email, id);

            if (revision == null)
            {
                TempData.AddFlash("The requested revision doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Show
            {
                ClaId = claId,
                Id = id,
                Number = revision.Number,
                Text = revision.Text,
                RequireAddress = revision.RequireAddress
            });
        }
    }
}

Views/Clas/Create.cshtml
@model CLAM.Models.View.Clas.Create
@{
    ViewBag.Title = "Create CLA";
}
<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ApiKey"></label>
        <input class="form-control" asp-for="ApiKey">
        <span asp-validation-for="ApiKey" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">Create</button>
</form>

Views/Clas/Edit.cshtml
@model CLAM.Models.View.Clas.Edit
@{
    ViewBag.Title = "Edit CLA";
}
<form method="post" asp-action="Edit">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="ApiKey"></label>
        <input class="form-control" asp-for="ApiKey">
        <span asp-validation-for="ApiKey" class="text-danger"></span>
    </div>
    <button class="btn btn-primary">Edit</button>
</form>

Views/Clas/Index.cshtml
@model CLAM.Models.View.Clas.Index
@{
    ViewBag.Title = "CLAs";
}
@if (Model.Clas.Count == 0)
{
    <div class="alert alert-warning">
        No CLAs have been created yet.
    </div>
}
else
{
    <div class="list-group mb-3">
        @foreach (var cla in Model.Clas)
        {
            <a class="list-group-item list-group-item-action" asp-action="Show" asp-route-id="@cla.Id">@cla.Name</a>
        }
    </div>
}
<a class="btn btn-primary" asp-action="Create">Create</a>

Views/Clas/Show.cshtml
@model CLAM.Models.View.Clas.Show
@{
    ViewBag.Title = "Show CLA";
}
<div class="form-group">
    <label asp-for="Name"></label>
    <input class="form-control" asp-for="Name" readonly>
</div>
<div class="form-group">
    <label asp-for="ApiKey"></label>
    <input class="form-control" asp-for="ApiKey" readonly>
</div>
<div class="form-group">
    <label asp-for="Secret"></label>
    <input class="form-control" asp-for="Secret" readonly>
</div>
<div class="form-group">
    <label asp-for="WebhookUrl"></label>
    <input class="form-control" asp-for="WebhookUrl" readonly>
</div>
<a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
<a class="btn btn-outline-primary" asp-controller="Revisions" asp-action="Index" asp-route-claid="@Model.Id">Revisions</a>