Models/Database/Revision.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.Database
{
    public class Revision : IModel
    {
        public int Id { get; set; }

        public int ClaId { get; set; }

        public int Number { get; set; }

        [Required]
        public string Text { get; set; }

        public bool RequireAddress { get; set; }

        public DateTime CreatedAt { get; set; }

        public DateTime? ModifiedAt { get; set; }

        public DateTime? DeletedAt { get; set; }

        public Cla Cla { get; set; }

        public List<Signer> Signers { get; set; }

        public static void ConfigureEntity(EntityTypeBuilder<Revision> builder)
        {
            builder.HasQueryFilter(u => !u.DeletedAt.HasValue);
        }
    }
}

Models/View/Clas/Create.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Clas
{
    public class Create
    {
        [Required, DisplayName("Name")]
        public string Name { get; set; }

        [Required, DisplayName("API key")]
        public string ApiKey { get; set; }
    }
}

Models/View/Clas/Show.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Clas
{
    public class Show
    {
        public int Id { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("API key")]
        public string ApiKey { get; set; }

        [DisplayName("Webhook secret")]
        public string Secret { get; set; }

        [DataType(DataType.Url), DisplayName("Webhook URL")]
        public string WebhookUrl { get; set; }
    }
}

Models/View/Revisions/Create.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Revisions
{
    public class Create
    {
        [Required, DisplayName("Text")]
        public string Text { get; set; }

        [DisplayName("Require address")]
        public bool RequireAddress { get; set; }
    }
}

Models/View/Revisions/Index.cs
using CLAM.Models.Database;
using System.Collections.Generic;

namespace CLAM.Models.View.Revisions
{
    public class Index
    {
        public List<Revision> Revisions { get; set; }
    }
}

Models/View/Revisions/Show.cs
using System.ComponentModel;

namespace CLAM.Models.View.Revisions
{
    public class Show
    {
        public int ClaId { get; set; }

        public int Id { get; set; }

        [DisplayName("Revision")]
        public int Number { get; set; }

        [DisplayName("Text")]
        public string Text { get; set; }

        [DisplayName("Require address")]
        public bool RequireAddress { get; set; }
    }
}

Models/View/Signers/Show.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CLAM.Models.View.Signers
{
    public class Show
    {
        [DataType(DataType.EmailAddress), DisplayName("Email address")]
        public string Email { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Signed at")]
        public DateTime? SignedAt { get; set; }
    }
}

Controllers/RevisionsController.cs
using CLAM.Extensions;
using CLAM.Models.View.Revisions;
using CLAM.Models.View.Shared;
using CLAM.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CLAM.Controllers
{
    [Route("clas/{claId}/revisions")]
    public class RevisionsController : Controller
    {
        public RevisionsController(RevisionService revisionService)
        {
            RevisionService = revisionService;
        }

        public RevisionService RevisionService { get; }

        [HttpGet, ActionName("Index"), Route("")]
        public async Task<IActionResult> GetIndex(int claId)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var revisions = await RevisionService.List(email, claId);

            return View(new Index
            {
                Revisions = revisions
            });
        }

        [HttpGet, ActionName("Create"), Route("create")]
        public IActionResult GetCreate()
        {
            return View();
        }

        [HttpPost, ActionName("Create"), Route("create")]
        public async Task<IActionResult> PostCreate(int claId, Create create)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var email = User.FindFirst(ClaimTypes.Email).Value;
            if (await RevisionService.Create(email, claId, create.Text, create.RequireAddress))
            {
                TempData.AddFlash("Your revision has been created", FlashType.Success);
            }
            else
            {
                TempData.AddFlash("Your revision couldn't be created", FlashType.Error);
            }

            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("Show"), Route("{id}/show")]
        public async Task<IActionResult> GetShow(int claId, int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var revision = await RevisionService.Single(email, id);

            if (revision == null)
            {
                TempData.AddFlash("The requested revision doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Show
            {
                ClaId = claId,
                Id = id,
                Number = revision.Number,
                Text = revision.Text,
                RequireAddress = revision.RequireAddress
            });
        }
    }
}

Controllers/SignersController.cs
using CLAM.Extensions;
using CLAM.Models.View.Shared;
using CLAM.Models.View.Signers;
using CLAM.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CLAM.Controllers
{
    [Route("clas/{claId}/revisions/{revisionId}/signers")]
    public class SignersController : Controller
    {
        public SignersController(SignerService signerService)
        {
            SignerService = signerService;
        }

        private SignerService SignerService { get; }

        [HttpGet, ActionName("Index"), Route("")]
        public async Task<IActionResult> GetIndex(int revisionId)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var signers = await SignerService.List(email, revisionId);

            return View(new Index
            {
                Signers = signers
            });
        }

        [HttpGet, ActionName("Show"), Route("{id}/show")]
        public async Task<IActionResult> GetShow(int id)
        {
            var email = User.FindFirst(ClaimTypes.Email).Value;
            var signer = await SignerService.Single(email, id);

            if (signer == null)
            {
                TempData.AddFlash("The requested signer doesn't exist", FlashType.Warning);
                return RedirectToAction("Index");
            }

            return View(new Show
            {
                Email = signer.Email,
                Name = signer.Name,
                Address = signer.Address,
                SignedAt = signer.SignedAt
            });
        }
    }
}

Views/Revisions/Create.cshtml
@model CLAM.Models.View.Revisions.Create
@{
    ViewBag.Title = "Create revision";
}
<form method="post" asp-action="Create">
    <div class="form-group">
        <label asp-for="Text"></label>
        <textarea class="form-control" asp-for="Text"></textarea>
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <div class="form-group">
        <div class="custom-control custom-checkbox">
            <input class="custom-control-input" asp-for="RequireAddress">
            <label class="custom-control-label" asp-for="RequireAddress"></label>
        </div>
    </div>
    <button class="btn btn-primary">Create</button>
</form>

Views/Revisions/Index.cshtml
@model CLAM.Models.View.Revisions.Index
@{
    ViewBag.Title = "Revisions";
}
@if (Model.Revisions.Count == 0)
{
    <div class="alert alert-warning">
        No revisions have been created yet.
    </div>
}
else
{
    <div class="list-group mb-3">
        @foreach (var revision in Model.Revisions)
        {
            <a class="list-group-item list-group-item-action" asp-action="Show" asp-route-id="@revision.Id">Revision @revision.Number</a>
        }
    </div>
}
<a class="btn btn-primary" asp-action="Create">Create</a>

Views/Revisions/Show.cshtml
@model CLAM.Models.View.Revisions.Show
@{
    ViewBag.Title = "Show revision";
}
<div class="form-group">
    <label asp-for="Number"></label>
    <input class="form-control" asp-for="Number" readonly>
</div>
<div class="form-group">
    <label asp-for="Text"></label>
    <textarea class="form-control" asp-for="Text" readonly></textarea>
</div>
<div class="form-group">
    <div class="custom-control custom-checkbox">
        <input class="custom-control-input" asp-for="RequireAddress" readonly>
        <label class="custom-control-label" asp-for="RequireAddress"></label>
    </div>
</div>
<a class="btn btn-outline-primary" asp-controller="Signers" asp-action="Index" asp-route-claid="@Model.ClaId" asp-route-revisionid="@Model.Id">Signers</a>